# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-07 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('photo', models.CharField(max_length=200, null=True)),
                ('post_data', models.DateTimeField(default=datetime.datetime.now)),
                ('board_like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('post_data', models.DateTimeField(default=datetime.datetime.now)),
                ('groud_id', models.IntegerField(default=1)),
                ('depth', models.IntegerField(default=1)),
                ('comment_like', models.IntegerField(default=0)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.Board')),
            ],
        ),
        migrations.CreateModel(
            name='LikeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(default=datetime.datetime.now)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.Board')),
            ],
        ),
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=12)),
                ('profile_photo', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='likecomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.User'),
        ),
        migrations.AddField(
            model_name='likeboard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.User'),
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.User'),
        ),
    ]
